server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

vertexflow:
  ai:
    enabled: true
    provider: openai-compatible
    api-key: ${DEEPSEEK_API_KEY}
    base-url: https://api.deepseek.com/v1
    model: deepseek-chat
    temperature: 0.7
    max-tokens: 2048
    console-log: true

    memory:
      enabled: true
      #      type: window：走本地窗口记忆，redis：走redis记忆
      type: redis
      max-messages: 20
      conversation-id: spring-redis-user
      redis:
        host: localhost
        port: 6379
        password:
        database: 0
        key-prefix: vertexflow:chat-memory
        ttl-seconds: 86400

    rag:
      enabled: true
      top-k: 3
      return-sources: true
      chunk-size: 300
      overlap: 50
      document-location: vertexflow-ai-spring-boot-example/src/main/resources/docs
      document-urls:
        - https://example.com
#type: memory：走内存，qdrant：走向量数据库
    vector-store:
      type: qdrant
      qdrant:
        url: http://localhost:6333
        collection-name: vertexflow_docs
        vector-size: 256

    tool:
      enabled: true
      max-steps: 10
      react-enabled: true
      react-allow-json-action-input: true
      react-retry-on-format-error: true